spring:
  thymeleaf:
    mode: html
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.75.221:3306/CAT?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: xjy
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
server:
  servlet:
    context-path: /
    session:
      timeout: 604800
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xjy.cat.model
